version: 2
updates:
    - package-ecosystem: "uv" # See documentation for possible values
      target-branch: "main"
      directory: "/" # Location of package manifests
      schedule:
          interval: "daily"
groups:
    dependencies:
        applies-to: version-updates
        patterns:
            - "*"