version: 2
updates:
    - package-ecosystem: "uv" # See documentation for possible values
      target-branch: "main"
      directory: "/" # Location of package manifests
      schedule:
          interval: "daily"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      dependencies:
        applies-to: version-updates
        patterns:
            - "*"