services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=password
  api:
    image: cutedog5695/api:main
    restart: unless-stopped
    ports:
      - 8000:8000
    enviroment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - MONGO=mongodb://api:password@mongodb:27017/?directConnection=true